version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(name)s - %(levelname)s - %(message)s"
  precise:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
#  logging.handlers.RotatingFileHandler
    class: logging.FileHandler
    level: DEBUG
    formatter: precise
    filename: backupDirs.log
    encoding: utf8
    mode: a

loggers:
  web_scraper:
      level: DEBUG
      handlers: [file]
      propagate: no

root:
  level: DEBUG
  handlers: [console,file]
